language: node_js
before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3 # give xvfb some time to start
 - webpack
node_js:
  - "6"
services:
  - mongodb
script:
  - if [ $TRAVIS_EVENT_TYPE -eq "cron" ] ; then npm run test-e2e; else npm test; fi
