version: '2'
services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "6001:6001"
    environment:
      DATABASE_URL: "mongodb://mongo"
  mongo:
    image: mongo:3.0